name = "BenchSweeps"
uuid = "5f68b540-f839-11e8-2b2e-95480b97dfbf"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
